# Generated by Django 3.1.7 on 2021-02-28 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of product')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Descrip')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Type of display')),
                ('resolution', models.CharField(max_length=255, verbose_name='Pix of display')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Battery')),
                ('ram', models.CharField(max_length=255, verbose_name='OP')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=255, verbose_name='Max OP')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Main Camera')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Front Camera')),
                ('cateroty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.catagory', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of product')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Descrip')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Type of display')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Processor')),
                ('ram', models.CharField(max_length=255, verbose_name='OP')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Time battery')),
                ('cateroty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.catagory', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
